Repository ultralytics/tinder, pull requests merged in 2025-01, with the labels that each got.

#18 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#20 Apply `ruff==0.9.0` formatting
  features.py
Labels: enhancement, devops

#21 Standardize license headers in Python files
  fb_auth_token.py
  features.py
  phone_auth_token.py
  test.py
  tinder_api.py
  tinder_api_sms.py
Labels: documentation

#22 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
Labels: devops, documentation
